/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import rccms.common.domain.Church;
import rccms.common.domain.Inspection;
import rccms.common.service.ChurchService;
import rccms.common.service.InspectionService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;

/**
 *
 * @author IT MODERN LTD
 */
public class AnalyticsForm extends javax.swing.JFrame {

    private ChurchService churchService;
    private InspectionService inspectionService;
    private DefaultTableModel tableModel;

    /**
     * Creates new form AnalyticsForm
     */
    public AnalyticsForm() {
        initComponents();

        analyticsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Metric", "Value"
                }));

        // ... your existing action listeners ...
        try {
            churchService = rccms.client.util.RMIClientUtil.getChurchService();
            inspectionService = rccms.client.util.RMIClientUtil.getInspectionService();
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error connecting to server: " + e.getMessage());
        }
        tableModel = (DefaultTableModel) analyticsTable.getModel();
        generateAnalytics();

        styleForm();              // ADD THIS LINE
        setLocationRelativeTo(null); // ADD THIS LINE - Centers the window
    }

    private void generateAnalytics() {
        tableModel.setRowCount(0);

        List<Church> churches = null;
        List<Inspection> inspections = null;
        try {
            if (churchService != null) churches = churchService.findAll();
            if (inspectionService != null) inspections = inspectionService.findAll();
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (churches == null) churches = java.util.Collections.emptyList();
        if (inspections == null) inspections = java.util.Collections.emptyList();

        int totalChurches = churches.size();
        int totalInspections = inspections.size();

        int compliant = 0;
        int nonCompliant = 0;
        int pending = 0;

        double totalScore = 0;
        int scoredInspections = 0;

        for (Church church : churches) {
            if ("COMPLIANT".equals(church.getComplianceStatus())) {
                compliant++;
            } else if ("NON_COMPLIANT".equals(church.getComplianceStatus())) {
                nonCompliant++;
            } else {
                pending++;
            }
        }

        for (Inspection inspection : inspections) {
            if (inspection.getOverallScore() > 0) {
                totalScore += inspection.getOverallScore();
                scoredInspections++;
            }
        }

        double avgScore = scoredInspections > 0 ? totalScore / scoredInspections : 0;
        double complianceRate = totalChurches > 0 ? (compliant * 100.0 / totalChurches) : 0;

        Object[] row1 = {"Total Churches", String.valueOf(totalChurches)};
        Object[] row2 = {"Total Inspections", String.valueOf(totalInspections)};
        Object[] row3 = {"Compliant Churches", String.valueOf(compliant)};
        Object[] row4 = {"Non-Compliant Churches", String.valueOf(nonCompliant)};
        Object[] row5 = {"Pending Churches", String.valueOf(pending)};
        Object[] row6 = {"Compliance Rate", String.format("%.2f%%", complianceRate)};
        Object[] row7 = {"Average Inspection Score", String.format("%.2f%%", avgScore)};

        tableModel.addRow(row1);
        tableModel.addRow(row2);
        tableModel.addRow(row3);
        tableModel.addRow(row4);
        tableModel.addRow(row5);
        tableModel.addRow(row6);
        tableModel.addRow(row7);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        analyticsTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        analyticsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Total churches", "Total Inspection", "Compliant Churches", "Non-Compliant Churches", "Pending Churches", "Compliant Rate", " Average Inspection Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(analyticsTable);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton)
                        .addGap(5, 5, 5)
                        .addComponent(closeButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton)
                    .addComponent(closeButton))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("System Analytics");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 513, Short.MAX_VALUE)
                        .addComponent(btnBack)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        generateAnalytics();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //this.dispose();
        new DashboardForm().setVisible(true);

    }//GEN-LAST:event_btnBackActionPerformed


    private void styleForm() {
        // Define color scheme (matching all other forms)
        Color wintergreenDream = new Color(95, 140, 130);    // Main background
        Color laurelGreen = new Color(168, 186, 169);        // Panel background
        Color dutchWhite = new Color(229, 221, 194);         // Input fields
        Color darkAccent = new Color(40, 60, 55);            // Text and buttons
        Color buttonHover = new Color(75, 120, 110);         // Button hover state

        // Set main form background
        getContentPane().setBackground(wintergreenDream);

        // Style main panel
        jPanel1.setBackground(laurelGreen);
        jPanel1.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(darkAccent, 2),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));

        // Style main title label
        jLabel1.setForeground(darkAccent);
        jLabel1.setFont(new Font("Dialog", Font.BOLD, 24));

        // Style table
        analyticsTable.setBackground(dutchWhite);
        analyticsTable.setForeground(darkAccent);
        analyticsTable.setSelectionBackground(wintergreenDream);
        analyticsTable.setSelectionForeground(Color.WHITE);
        analyticsTable.setGridColor(laurelGreen);
        analyticsTable.setFont(new Font("Dialog", Font.PLAIN, 12));
        analyticsTable.setRowHeight(28);

        // Style table header
        analyticsTable.getTableHeader().setBackground(wintergreenDream);
        analyticsTable.getTableHeader().setForeground(Color.WHITE);
        analyticsTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 14));

        // Style scroll pane
        jScrollPane2.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
        jScrollPane2.getViewport().setBackground(dutchWhite);

        // Style buttons
        styleButton(refreshButton, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(closeButton, new Color(180, 80, 80), Color.WHITE, new Color(200, 60, 60)); // Red for close
        styleButton(btnBack, darkAccent, Color.WHITE, new Color(60, 80, 75));
    }

    private void styleButton(javax.swing.JButton button, Color background,
            Color foreground, Color hoverColor) {
        button.setBackground(background);
        button.setForeground(foreground);
        button.setFont(new Font("Dialog", Font.BOLD, 12));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground.darker(), 1),
                BorderFactory.createEmptyBorder(8, 15, 8, 15)
        ));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverColor);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(background);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable analyticsTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
