/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rccms.common.domain.Church;
import rccms.common.service.ChurchService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;

/**
 *
 * @author IT MODERN LTD
 */
public class ChurchManagementForm extends javax.swing.JFrame {

    private ChurchService churchService;
    private DefaultTableModel tableModel;

    /**
     * Creates new form ChurchManagementForm
     */
    public ChurchManagementForm() {
        initComponents();
        // churchService is initialized via RMI on demand or we can get it here
        // churchService = new ChurchService(); // Cannot instantiate interface
        
        tableModel = (DefaultTableModel) churchTable.getModel();

        tableModel.setRowCount(0);
        tableModel.setColumnCount(0);
        tableModel.addColumn("ID");
        tableModel.addColumn("Church Name");
        tableModel.addColumn("Registration Number");
        tableModel.addColumn("Pastor Name");
        tableModel.addColumn("Pastor Phone");
        tableModel.addColumn("District");
        tableModel.addColumn("Capacity");
        tableModel.addColumn("Building Type");
        tableModel.addColumn("Compliance Status");

        loadChurches();

        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);

        styleForm();
        setLocationRelativeTo(null);
    }

    private void loadChurches() {
        if (tableModel == null) {
            tableModel = (DefaultTableModel) churchTable.getModel();
        }

        tableModel.setRowCount(0);
        try {
            churchService = rccms.client.util.RMIClientUtil.getChurchService();
            if (churchService != null) {
                List<Church> churches = churchService.findAll();
                for (Church church : churches) {
                    Object[] row = {
                        church.getChurchId(),
                        church.getChurchName(),
                        church.getRegistrationNumber(),
                        church.getPastorName(),
                        church.getPastorPhone(),
                        church.getDistrict(),
                        church.getCapacity(),
                        church.getBuildingType(),
                        church.getComplianceStatus()
                    };
                    tableModel.addRow(row);
                }
            } else {
                 JOptionPane.showMessageDialog(this, "Could not connect to server.", "Connection Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading churches: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtChurchName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRegistrationNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPastorName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPastorEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPastorPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDistrict = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSector = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCell = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        cmbBuildingType = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtChurchID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        churchTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(15000, 1000));
        setPreferredSize(new java.awt.Dimension(1500, 1000));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Church Details"));

        jLabel2.setText("Church Name:");

        jLabel3.setText("Registration Number:");

        txtRegistrationNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Pastor Name:");

        jLabel5.setText("Pastor Phone:");

        jLabel6.setText("Pastor Email:");

        jLabel7.setText("Address:");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel8.setText("District:");

        jLabel9.setText("Sector:");

        jLabel10.setText("Cell:");

        jLabel11.setText("Capacity:");

        cmbBuildingType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PERMANENT", "TEMPORARY", "RENTED" }));

        jLabel12.setText("Building Type:");

        jLabel14.setText("Church ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel5))))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCapacity)
                                    .addComponent(txtAddress)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPastorName, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(txtRegistrationNumber)
                                            .addComponent(txtChurchName)
                                            .addComponent(txtPastorEmail)
                                            .addComponent(txtPastorPhone)
                                            .addComponent(txtChurchID))))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel12)
                                .addGap(39, 39, 39)
                                .addComponent(cmbBuildingType, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSector, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(txtDistrict)
                                    .addComponent(txtCell))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(cmbBuildingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtChurchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(txtChurchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegistrationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPastorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPastorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPastorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtSector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        churchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        churchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                churchTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(churchTable);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Church Search"));

        jLabel13.setText("Church ID");

        btnsearch.setText("search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsearch)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Church Management");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(625, 625, 625)
                .addComponent(btnAdd)
                .addGap(5, 5, 5)
                .addComponent(btnUpdate)
                .addGap(5, 5, 5)
                .addComponent(btnDelete)
                .addGap(5, 5, 5)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(905, 905, 905)
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(933, 933, 933))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!validateInputs()) {
            return;
        }

        try {
            Church church = new Church();
            church.setChurchName(txtChurchName.getText().trim());
            church.setRegistrationNumber(txtRegistrationNumber.getText().trim());
            church.setPastorName(txtPastorName.getText().trim());
            church.setPastorPhone(txtPastorPhone.getText().trim());
            church.setPastorEmail(txtPastorEmail.getText().trim());
            church.setAddress(txtAddress.getText().trim());
            church.setDistrict(txtDistrict.getText().trim());
            church.setSector(txtSector.getText().trim());
            church.setCell(txtCell.getText().trim());
            church.setCapacity(Integer.parseInt(txtCapacity.getText().trim()));
            church.setBuildingType(cmbBuildingType.getSelectedItem().toString());
            church.setComplianceStatus("PENDING");
            church.setRegistrationDate(new Date());

            if (church.getCapacity() <= 0) {
                JOptionPane.showMessageDialog(this, "Capacity must be greater than 0!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (churchService.existsByRegistrationNumber(church.getRegistrationNumber())) {
                JOptionPane.showMessageDialog(this, "Registration number already exists!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (churchService.create(church)) {
                JOptionPane.showMessageDialog(this, "Church added successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadChurches();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add church!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
             e.printStackTrace();
             JOptionPane.showMessageDialog(this, "Error creating church: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        // Check if Church ID field has a value
        if (txtChurchID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search for or select a church to delete!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this church?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                // Get Church ID from the text field instead of table selection
                int churchId = Integer.parseInt(txtChurchID.getText().trim());

                churchService = rccms.client.util.RMIClientUtil.getChurchService();
                if (churchService.delete(churchId)) {
                    JOptionPane.showMessageDialog(this, "Church deleted successfully!",
                            "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadChurches();
                    clearFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete church!",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid Church ID!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
                 JOptionPane.showMessageDialog(this, "Error deleting church: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        // Check if Church ID field has a value
        if (txtChurchID.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search for or select a church to update!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validateInputs()) {
            return;
        }

        try {
            // Get Church ID from the text field instead of table selection
            int churchId = Integer.parseInt(txtChurchID.getText().trim());
            churchService = rccms.client.util.RMIClientUtil.getChurchService();
            Church church = churchService.findById(churchId);

            if (church == null) {
                JOptionPane.showMessageDialog(this, "Church not found!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            church.setChurchName(txtChurchName.getText().trim());
            church.setRegistrationNumber(txtRegistrationNumber.getText().trim());
            church.setPastorName(txtPastorName.getText().trim());
            church.setPastorEmail(txtPastorEmail.getText().trim());
            church.setPastorPhone(txtPastorPhone.getText().trim());
            church.setAddress(txtAddress.getText().trim());
            church.setDistrict(txtDistrict.getText().trim());
            church.setSector(txtSector.getText().trim());
            church.setCell(txtCell.getText().trim());
            church.setCapacity(Integer.parseInt(txtCapacity.getText().trim()));
            church.setBuildingType(cmbBuildingType.getSelectedItem().toString());

            if (churchService.update(church)) {
                JOptionPane.showMessageDialog(this, "Church updated successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadChurches();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update church!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid Church ID or capacity value!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error updating church: " + e.getMessage());
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void churchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_churchTableMouseClicked
        int selectedRow = churchTable.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                churchService = rccms.client.util.RMIClientUtil.getChurchService();
                Church church = churchService.findById((Integer) tableModel.getValueAt(selectedRow, 0));
                if (church != null) {
                    txtChurchID.setText(String.valueOf(church.getChurchId()));
                    txtChurchName.setText(church.getChurchName());
                    txtRegistrationNumber.setText(church.getRegistrationNumber());
                    txtPastorName.setText(church.getPastorName());
                    txtPastorEmail.setText(church.getPastorEmail());
                    txtPastorPhone.setText(church.getPastorPhone());
                    txtAddress.setText(church.getAddress());
                    txtDistrict.setText(church.getDistrict());
                    txtSector.setText(church.getSector());
                    txtCell.setText(church.getCell());
                    txtCapacity.setText(String.valueOf(church.getCapacity()));
                    cmbBuildingType.setSelectedItem(church.getBuildingType());
                    btnUpdate.setEnabled(true);
                    btnDelete.setEnabled(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_churchTableMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed

        String idText = txtSearch.getText().trim();

        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Church ID");
            return;
        }

        try {
            int churchId = Integer.parseInt(idText);

            // Call the service to find the church
            churchService = rccms.client.util.RMIClientUtil.getChurchService();
            Church church = churchService.findById(churchId);

            if (church != null) {
                // Populate church details in the form fields
                populateChurchDetails(church);

                // Enable update and delete buttons
                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);

                JOptionPane.showMessageDialog(this, "Church found! You can now update or delete the record.");

            } else {
                JOptionPane.showMessageDialog(this, "No church found with ID: " + churchId);
                clearFields(); // Use clearFields instead of clearDetailFields
                btnUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid ID. Only numbers allowed.");
            clearFields(); // Use clearFields instead of clearDetailFields
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error finding church: " + e.getMessage());
        }

    }

// Method to populate church details in form fields
    private void populateChurchDetails(Church church) {
        txtChurchID.setText(String.valueOf(church.getChurchId()));
        txtChurchName.setText(church.getChurchName());
        txtRegistrationNumber.setText(church.getRegistrationNumber());
        txtPastorName.setText(church.getPastorName());
        txtPastorEmail.setText(church.getPastorEmail());
        txtPastorPhone.setText(church.getPastorPhone());
        txtDistrict.setText(church.getDistrict());
        txtSector.setText(church.getSector());
        txtCell.setText(church.getCell());
        txtAddress.setText(church.getAddress());
        txtCapacity.setText(String.valueOf(church.getCapacity()));

        // Set building type in combo box
        cmbBuildingType.setSelectedItem(church.getBuildingType());
    }

// Validation method
// Refresh table with all data
    private void refreshTable() {
        tableModel.setRowCount(0);
        List<Church> churches = null;
        try {
             if (churchService == null) churchService = rccms.client.util.RMIClientUtil.getChurchService();
             churches = churchService.findAll();
        } catch (Exception e) {
             e.printStackTrace();
             churches = java.util.Collections.emptyList();
        }
        for (Church church : churches) {
            Object[] row = {
                church.getChurchId(),
                church.getChurchName(),
                church.getRegistrationNumber(),
                church.getPastorName(),
                church.getPastorPhone(),
                church.getPastorEmail(),
                church.getAddress(),
                church.getDistrict(),
                church.getSector(),
                church.getCell(),
                church.getCapacity(),
                church.getBuildingType(),
                church.getComplianceStatus(),
                church.getRegistrationDate(),
                church.getLastInspectionDate()
            };
            tableModel.addRow(row);
        }


    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new DashboardForm().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private boolean validateInputs() {
        if (txtChurchName.getText().trim().isEmpty()
                || txtRegistrationNumber.getText().trim().isEmpty()
                || txtPastorName.getText().trim().isEmpty()
                || txtPastorEmail.getText().trim().isEmpty()
                || txtPastorPhone.getText().trim().isEmpty()
                || txtAddress.getText().trim().isEmpty()
                || txtDistrict.getText().trim().isEmpty()
                || txtSector.getText().trim().isEmpty()
                || txtCell.getText().trim().isEmpty()
                || txtCapacity.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            int capacity = Integer.parseInt(txtCapacity.getText().trim());
            if (capacity <= 0) {
                JOptionPane.showMessageDialog(this, "Capacity must be greater than 0!",
                        "Validation Error", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Capacity must be a valid number!",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    private void clearFields() {

        // Clears all text input fields
        txtChurchID.setText("");
        txtChurchName.setText("");
        txtRegistrationNumber.setText("");
        txtPastorName.setText("");
        txtPastorEmail.setText("");
        txtPastorPhone.setText("");
        txtAddress.setText("");
        txtDistrict.setText("");
        txtSector.setText("");
        txtCell.setText("");
        txtCapacity.setText("");
        txtSearch.setText("");

        // Resets combo box to first option (PERMANENT)
        cmbBuildingType.setSelectedIndex(0);

        // Removes any selected row highlighting in the table
        churchTable.clearSelection();

        // Button state management
        btnUpdate.setEnabled(false);  // Disables Update button
        btnDelete.setEnabled(false);  // Disables Delete button
        btnAdd.setEnabled(true);      // Enables Add button

    }

    private void styleForm() {
        // Define color scheme (matching all other forms)
        Color wintergreenDream = new Color(95, 140, 130);    // Main background
        Color laurelGreen = new Color(168, 186, 169);        // Panel background
        Color dutchWhite = new Color(229, 221, 194);         // Input fields
        Color darkAccent = new Color(40, 60, 55);            // Text and buttons
        Color buttonHover = new Color(75, 120, 110);         // Button hover state

        // Set main form background
        getContentPane().setBackground(wintergreenDream);

        // Style main panels
        jPanel1.setBackground(wintergreenDream);
        jPanel2.setBackground(laurelGreen);
        jPanel4.setBackground(laurelGreen);

        // Style panel borders
        jPanel2.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(darkAccent, 2),
                "Church Details",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new Font("Dialog", Font.BOLD, 12),
                darkAccent
        ));

        jPanel4.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(darkAccent, 2),
                "Church Search",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new Font("Dialog", Font.BOLD, 12),
                darkAccent
        ));

        // Style main title label
        jLabel1.setForeground(darkAccent);
        jLabel1.setFont(new Font("Dialog", Font.BOLD, 24));

        // Style all form labels
        styleLabel(jLabel2, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel3, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel4, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel5, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel6, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel7, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel8, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel9, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel10, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel11, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel12, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel13, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel14, darkAccent, 12, Font.PLAIN);

        // Style all text fields
        styleTextField(txtChurchID, dutchWhite, darkAccent);
        styleTextField(txtChurchName, dutchWhite, darkAccent);
        styleTextField(txtRegistrationNumber, dutchWhite, darkAccent);
        styleTextField(txtPastorName, dutchWhite, darkAccent);
        styleTextField(txtPastorEmail, dutchWhite, darkAccent);
        styleTextField(txtPastorPhone, dutchWhite, darkAccent);
        styleTextField(txtAddress, dutchWhite, darkAccent);
        styleTextField(txtDistrict, dutchWhite, darkAccent);
        styleTextField(txtSector, dutchWhite, darkAccent);
        styleTextField(txtCell, dutchWhite, darkAccent);
        styleTextField(txtCapacity, dutchWhite, darkAccent);
        styleTextField(txtSearch, dutchWhite, darkAccent);

        // Style combo box
        cmbBuildingType.setBackground(dutchWhite);
        cmbBuildingType.setForeground(darkAccent);
        cmbBuildingType.setFont(new Font("Dialog", Font.PLAIN, 12));
        cmbBuildingType.setBorder(BorderFactory.createLineBorder(darkAccent, 1));

        // Style table
        churchTable.setBackground(dutchWhite);
        churchTable.setForeground(darkAccent);
        churchTable.setSelectionBackground(wintergreenDream);
        churchTable.setSelectionForeground(Color.WHITE);
        churchTable.setGridColor(laurelGreen);
        churchTable.setFont(new Font("Dialog", Font.PLAIN, 11));
        churchTable.setRowHeight(25);

        // Style table header
        churchTable.getTableHeader().setBackground(wintergreenDream);
        churchTable.getTableHeader().setForeground(Color.WHITE);
        churchTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 12));

        // Style scroll pane
        jScrollPane2.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
        jScrollPane2.getViewport().setBackground(dutchWhite);

        // Style buttons with smart color coding
        styleButton(btnAdd, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(btnUpdate, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(btnDelete, new Color(180, 80, 80), Color.WHITE, new Color(200, 60, 60)); // Red for delete
        styleButton(btnClear, laurelGreen, darkAccent, new Color(150, 170, 151));
        styleButton(btnsearch, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(btnBack, darkAccent, Color.WHITE, new Color(60, 80, 75));
    }

    private void styleLabel(javax.swing.JLabel label, Color foreground, int size, int style) {
        label.setForeground(foreground);
        label.setFont(new Font("Dialog", style, size));
    }

    private void styleTextField(javax.swing.JTextField textField, Color background, Color foreground) {
        textField.setBackground(background);
        textField.setForeground(foreground);
        textField.setCaretColor(foreground);
        textField.setFont(new Font("Dialog", Font.PLAIN, 12));
        textField.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground, 1),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
        ));
    }

    private void styleButton(javax.swing.JButton button, Color background,
            Color foreground, Color hoverColor) {
        button.setBackground(background);
        button.setForeground(foreground);
        button.setFont(new Font("Dialog", Font.BOLD, 12));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground.darker(), 1),
                BorderFactory.createEmptyBorder(8, 15, 8, 15)
        ));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverColor);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(background);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnsearch;
    private javax.swing.JTable churchTable;
    private javax.swing.JComboBox cmbBuildingType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtCell;
    private javax.swing.JTextField txtChurchID;
    private javax.swing.JTextField txtChurchName;
    private javax.swing.JTextField txtDistrict;
    private javax.swing.JTextField txtPastorEmail;
    private javax.swing.JTextField txtPastorName;
    private javax.swing.JTextField txtPastorPhone;
    private javax.swing.JTextField txtRegistrationNumber;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSector;
    // End of variables declaration//GEN-END:variables
}
