/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import rccms.common.domain.Church;
import rccms.common.service.ChurchService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;

/**
 *
 * @author IT MODERN LTD
 */
public class ComplianceReportForm extends javax.swing.JFrame {

    private ChurchService churchService;
    private DefaultTableModel tableModel;

    /**
     * Creates new form ComplianceReportForm
     */
    public ComplianceReportForm() {
        initComponents();

        // IMPORTANT: Override the table model created by initComponents()
        // This sets up 7 columns to match the 7 data fields
        reportTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String[]{
                    "Church ID", "Church Name", "Registration No.", "District",
                    "Compliance Status",
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class, java.lang.Object.class,
                java.lang.Double.class
            };

            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

        // Initialize the church service
        try {
            churchService = rccms.client.util.RMIClientUtil.getChurchService();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Get reference to the table model we just created
        tableModel = (DefaultTableModel) reportTable.getModel();

        // Load the data into the table
        generateReport();

        // Apply custom styling
        styleForm();

        // Center the window on screen
        setLocationRelativeTo(null);
    }

    private void generateReport() {
        tableModel.setRowCount(0);
        List<Church> churches;
        try {
            if (churchService == null) churchService = rccms.client.util.RMIClientUtil.getChurchService();
            churches = churchService.findAll();
        } catch (Exception e) {
            e.printStackTrace();
            churches = java.util.Collections.emptyList();
        }

        int compliant = 0;
        int nonCompliant = 0;
        int pending = 0;

        for (Church church : churches) {
            Object[] row = {
                church.getChurchId(),
                church.getChurchName(),
                church.getRegistrationNumber(),
                church.getDistrict(),
                church.getComplianceStatus()
            // Removed the two fields that don't exist
            };
            tableModel.addRow(row);

            if ("COMPLIANT".equals(church.getComplianceStatus())) {
                compliant++;
            } else if ("NON_COMPLIANT".equals(church.getComplianceStatus())) {
                nonCompliant++;
            } else {
                pending++;
            }
        }

        int total = churches.size();
        double compliantPercent = total > 0 ? (compliant * 100.0 / total) : 0;

        summaryLabel.setText(String.format(
                "<html>Total Churches: %d<br>"
                + "Compliant: %d (%.2f%%)<br>"
                + "Non-Compliant: %d<br>"
                + "Pending: %d</html>",
                total, compliant, compliantPercent, nonCompliant, pending
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        summaryLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Compliance Report");

        summaryLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        summaryLabel.setText("Summary");

        refreshButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Church Id", "Church Name", "Registration Number", "District", "Compliance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(reportTable);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(summaryLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(refreshButton)
                                .addGap(5, 5, 5)
                                .addComponent(closeButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addComponent(summaryLabel)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton)
                    .addComponent(closeButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        generateReport();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        new DashboardForm().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    private void styleForm() {
        // Define color scheme (matching all other forms)
        Color wintergreenDream = new Color(95, 140, 130);    // Main background
        Color laurelGreen = new Color(168, 186, 169);        // Panel background
        Color dutchWhite = new Color(229, 221, 194);         // Input fields
        Color darkAccent = new Color(40, 60, 55);            // Text and buttons
        Color buttonHover = new Color(75, 120, 110);         // Button hover state

        // Set main form background
        getContentPane().setBackground(wintergreenDream);

        // Style panel
        jPanel1.setBackground(laurelGreen);
        jPanel1.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(darkAccent, 2),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));

        // Style labels
        jLabel1.setForeground(darkAccent);
        jLabel1.setFont(new Font("Dialog", Font.BOLD, 24));

        summaryLabel.setForeground(darkAccent);
        summaryLabel.setFont(new Font("Dialog", Font.BOLD, 14));
        summaryLabel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(darkAccent, 1),
                BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        summaryLabel.setOpaque(true);
        summaryLabel.setBackground(dutchWhite);

        // Style table
        reportTable.setBackground(dutchWhite);
        reportTable.setForeground(darkAccent);
        reportTable.setSelectionBackground(wintergreenDream);
        reportTable.setSelectionForeground(Color.WHITE);
        reportTable.setGridColor(laurelGreen);
        reportTable.setFont(new Font("Dialog", Font.PLAIN, 11));
        reportTable.setRowHeight(25);

        // Style table header
        reportTable.getTableHeader().setBackground(wintergreenDream);
        reportTable.getTableHeader().setForeground(Color.WHITE);
        reportTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 12));

        // Style scroll pane
        jScrollPane2.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
        jScrollPane2.getViewport().setBackground(dutchWhite);

        // Style buttons
        styleButton(refreshButton, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(closeButton, new Color(180, 80, 80), Color.WHITE, new Color(200, 60, 60)); // Red for close
        styleButton(btnBack, darkAccent, Color.WHITE, new Color(60, 80, 75));
    }

    private void styleButton(javax.swing.JButton button, Color background,
            Color foreground, Color hoverColor) {
        button.setBackground(background);
        button.setForeground(foreground);
        button.setFont(new Font("Dialog", Font.BOLD, 12));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground.darker(), 1),
                BorderFactory.createEmptyBorder(8, 15, 8, 15)
        ));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverColor);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(background);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable reportTable;
    private javax.swing.JLabel summaryLabel;
    // End of variables declaration//GEN-END:variables
}
