/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import javax.swing.JOptionPane;
import rccms.common.service.AuthService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import rccms.client.util.UserSession;
import rccms.common.domain.User;

/**
 *
 * @author IT MODERN LTD
 */
public class DashboardForm extends javax.swing.JFrame {

    private AuthService authService;

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
        authService = new AuthService();
        User user = UserSession.getInstance().getUser();
        username.setText(user.getUsername().concat(" ," + user.getRole()));
        // ADD THESE 2 LINES:
        styleForm();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        churchMenuItem = new javax.swing.JMenuItem();
        inspectorMenuItem = new javax.swing.JMenuItem();
        standardMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        conductInspectionMenuItem = new javax.swing.JMenuItem();
        viewInspectionsMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        complianceReportMenuItem = new javax.swing.JMenuItem();
        analyticsMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        welcomeLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        welcomeLabel.setText("Welcome to RCCMS Dashboard");

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("<html><center>Rwanda Church Compliance and Monitoring System<br><br>Select an option from the menu to begin.</center></html>");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLabel)
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jPanel1.setBounds(24, 44, 760, 480);
        getContentPane().add(jPanel1);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT MODERN LTD\\Downloads\\3d-rendering-church-building(1) (2).jpg")); // NOI18N
        jLabel2.setBounds(0, 0, 800, 600);
        getContentPane().add(jLabel2);

        jMenu1.setText("User");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(logoutMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Management");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        churchMenuItem.setText("Church Management");
        churchMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                churchMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(churchMenuItem);

        inspectorMenuItem.setText("Inspector Management");
        inspectorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inspectorMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(inspectorMenuItem);

        standardMenuItem.setText("Inspection Standards");
        standardMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(standardMenuItem);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Inspection");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        conductInspectionMenuItem.setText("Conduct Inspection");
        conductInspectionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductInspectionMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(conductInspectionMenuItem);

        viewInspectionsMenuItem.setText("View Inspections");
        viewInspectionsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInspectionsMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(viewInspectionsMenuItem);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Reports");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        complianceReportMenuItem.setText("Compliance Report");
        complianceReportMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complianceReportMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(complianceReportMenuItem);

        analyticsMenuItem.setText("Analytics");
        analyticsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticsMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(analyticsMenuItem);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        authService.logout();
        this.dispose();
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        int option = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to exit?",
                "Exit Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void inspectorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inspectorMenuItemActionPerformed
        try {
            if (UserSession.getInstance().isAdmin()) {
                InspectorManagementForm form = new InspectorManagementForm();
                form.setVisible(true);
            } else {
                throw new Exception("Access Denied");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error opening Inspector Management: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_inspectorMenuItemActionPerformed

    private void churchMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_churchMenuItemActionPerformed
        try {
            if (UserSession.getInstance().isInspector()) {
                throw new Exception("Access Denied");

            }
            ChurchManagementForm form = new ChurchManagementForm();
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error opening Church Management: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_churchMenuItemActionPerformed

    private void standardMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardMenuItemActionPerformed
        try {
            StandardManagementForm form = new StandardManagementForm();
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error opening Standards Management: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_standardMenuItemActionPerformed

    private void conductInspectionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductInspectionMenuItemActionPerformed
        try {
            InspectionForm form = new InspectionForm();
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error opening Inspection Form: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_conductInspectionMenuItemActionPerformed

    private void viewInspectionsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInspectionsMenuItemActionPerformed
        try {
            InspectionListForm form = new InspectionListForm();
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error opening Inspection List: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewInspectionsMenuItemActionPerformed

    private void complianceReportMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complianceReportMenuItemActionPerformed
        try {
            ComplianceReportForm form = new ComplianceReportForm();
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error opening Compliance Report: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_complianceReportMenuItemActionPerformed

    private void analyticsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsMenuItemActionPerformed
        try {
            AnalyticsForm form = new AnalyticsForm();
            form.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error opening Analytics: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_analyticsMenuItemActionPerformed


    private void styleForm() {
        // Define colors
        Color wintergreenDream = new Color(95, 140, 130);
        Color laurelGreen = new Color(168, 186, 169);
        Color darkAccent = new Color(40, 60, 55);

        // Set backgrounds
        getContentPane().setBackground(wintergreenDream);
        jPanel1.setBackground(laurelGreen);
        jPanel1.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(darkAccent, 3),
                BorderFactory.createEmptyBorder(30, 30, 30, 30)
        ));

        // Style labels
        welcomeLabel.setForeground(darkAccent);
        jLabel1.setForeground(darkAccent);

        // Style menu bar
        jMenuBar2.setBackground(laurelGreen);
        jMenuBar2.setBorder(BorderFactory.createLineBorder(darkAccent, 2));

        // Style menus
        jMenu1.setForeground(darkAccent);
        jMenu2.setForeground(darkAccent);
        jMenu3.setForeground(darkAccent);
        jMenu4.setForeground(darkAccent);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem analyticsMenuItem;
    private javax.swing.JMenuItem churchMenuItem;
    private javax.swing.JMenuItem complianceReportMenuItem;
    private javax.swing.JMenuItem conductInspectionMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem inspectorMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuItem standardMenuItem;
    private javax.swing.JLabel username;
    private javax.swing.JMenuItem viewInspectionsMenuItem;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
