/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rccms.common.domain.Inspector;
import rccms.common.exception.DatabaseException;
import rccms.common.exception.ValidationException;
import rccms.common.service.InspectorService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;

/**
 *
 * @author IT MODERN LTD
 */
public class InspectorManagementForm extends javax.swing.JFrame {

    private InspectorService inspectorService;
    private DefaultTableModel tableModel;
    
    /**
     * Creates new form InspectorManagementForm
     */
    public InspectorManagementForm() {
    initComponents();
    // inspectorService = new InspectorService(); // Invalid interface instantiation
    initializeTable(); // Initialize the table model
    styleForm(); // Apply custom styling
    loadInspectors(); // Load initial data
}  
    private void initializeTable() {
    String[] columnNames = {"ID", "ID Number", "First Name", "Last Name", 
                           "Email", "Phone", "Qualifications", "District", "Status"};
    tableModel = new DefaultTableModel(columnNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Make table non-editable
        }
    };
    inspectorTable.setModel(tableModel);
}
    
     private void loadInspectors() {
        try {
            tableModel.setRowCount(0);
            inspectorService = rccms.client.util.RMIClientUtil.getInspectorService();
            if (inspectorService != null) {
                List<Inspector> inspectors = inspectorService.findAll();
                for (Inspector inspector : inspectors) {
                    Object[] row = {
                            inspector.getInspectorId(),
                            inspector.getInspectorIdNumber(),
                            inspector.getFirstName(),
                            inspector.getLastName(),
                            inspector.getEmail(),
                            inspector.getPhone(),
                            inspector.getQualifications(),
                            inspector.getAssignedDistrict(),
                            inspector.getEmploymentStatus()
                    };
                    tableModel.addRow(row);
                }
            } else {
                 JOptionPane.showMessageDialog(this, "Could not connect to server.", "Connection Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error loading inspectors: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idNumberField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qualificationsField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        districtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inspectorTable = new javax.swing.JTable();
        btnBackToDashboard = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtInspectorID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inspector Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ID Number:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Phone:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Qualifications:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("District:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Status:");

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVE", "INACTIVE", "SUSPENDED" }));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(districtField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(159, 159, 159))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(133, 133, 133))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idNumberField)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 289, Short.MAX_VALUE)
                            .addComponent(qualificationsField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phoneField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(5, 5, 5)
                        .addComponent(updateButton)
                        .addGap(5, 5, 5)
                        .addComponent(deleteButton)
                        .addGap(5, 5, 5)
                        .addComponent(clearButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(lastNameField)
                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(qualificationsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(districtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(clearButton))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Inspector Management");

        inspectorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        inspectorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inspectorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inspectorTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        btnBackToDashboard.setText("Back to Dashboard");
        btnBackToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inspector search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel10.setText("Inspector ID");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(33, 33, 33)
                .addComponent(txtInspectorID, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtInspectorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addComponent(jLabel10)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBackToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnBackToDashboard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!validateInputs())
            return;

        try {
            Inspector inspector = new Inspector();
            inspector.setInspectorIdNumber(idNumberField.getText().trim());
            inspector.setFirstName(firstNameField.getText().trim());
            inspector.setLastName(lastNameField.getText().trim());
            inspector.setEmail(emailField.getText().trim());
            inspector.setPhone(phoneField.getText().trim());
            inspector.setQualifications(qualificationsField.getText().trim());
            inspector.setAssignedDistrict(districtField.getText().trim());
            inspector.setEmploymentStatus(statusComboBox.getSelectedItem().toString());
            inspector.setUserId(0);

            inspectorService = rccms.client.util.RMIClientUtil.getInspectorService();
            inspectorService.create(inspector); // Modified to match interface method
            JOptionPane.showMessageDialog(this, "Inspector added successfully!",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            loadInspectors();
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
         int selectedRow = inspectorTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an inspector to update!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validateInputs())
            return;

        try {
            int inspectorId = (Integer) tableModel.getValueAt(selectedRow, 0);
            inspectorService = rccms.client.util.RMIClientUtil.getInspectorService();
            Inspector inspector = inspectorService.findById(inspectorId);

            if (inspector == null) {
                JOptionPane.showMessageDialog(this, "Inspector not found!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            inspector.setInspectorIdNumber(idNumberField.getText().trim());
            inspector.setFirstName(firstNameField.getText().trim());
            inspector.setLastName(lastNameField.getText().trim());
            inspector.setEmail(emailField.getText().trim());
            inspector.setPhone(phoneField.getText().trim());
            inspector.setQualifications(qualificationsField.getText().trim());
            inspector.setAssignedDistrict(districtField.getText().trim());
            inspector.setEmploymentStatus(statusComboBox.getSelectedItem().toString());

            inspectorService.update(inspector);
            JOptionPane.showMessageDialog(this, "Inspector updated successfully!",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
            loadInspectors();
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
         int selectedRow = inspectorTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select an inspector to delete!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this inspector?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                int inspectorId = (Integer) tableModel.getValueAt(selectedRow, 0);
                inspectorService = rccms.client.util.RMIClientUtil.getInspectorService();
                inspectorService.delete(inspectorId);
                JOptionPane.showMessageDialog(this, "Inspector deleted successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadInspectors();
                clearFields();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void inspectorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inspectorTableMouseClicked
       int selectedRow = inspectorTable.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                idNumberField.setText(tableModel.getValueAt(selectedRow, 1).toString());
                firstNameField.setText(tableModel.getValueAt(selectedRow, 2).toString());
                lastNameField.setText(tableModel.getValueAt(selectedRow, 3).toString());
                emailField.setText(tableModel.getValueAt(selectedRow, 4).toString());
                phoneField.setText(
                        tableModel.getValueAt(selectedRow, 5) != null ? tableModel.getValueAt(selectedRow, 5).toString()
                                : "");
                qualificationsField.setText(
                        tableModel.getValueAt(selectedRow, 6) != null ? tableModel.getValueAt(selectedRow, 6).toString()
                                : "");
                districtField.setText(tableModel.getValueAt(selectedRow, 7).toString());
                statusComboBox.setSelectedItem(tableModel.getValueAt(selectedRow, 8).toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error loading inspector data: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_inspectorTableMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchId = txtInspectorID.getText().trim();
    
    if (searchId.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
                "Please enter an Inspector ID to search!",
                "Input Required", 
                JOptionPane.WARNING_MESSAGE);
        txtInspectorID.requestFocus();
        return;
    }
    
    try {
        int inspectorId = Integer.parseInt(searchId);
        inspectorService = rccms.client.util.RMIClientUtil.getInspectorService();
        Inspector inspector = inspectorService.findById(inspectorId);
        
        if (inspector == null) {
            JOptionPane.showMessageDialog(this, 
                    "No inspector found with ID: " + inspectorId,
                    "Not Found", 
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        // Clear the table and show only the searched inspector
        tableModel.setRowCount(0);
        Object[] row = {
            inspector.getInspectorId(),
            inspector.getInspectorIdNumber(),
            inspector.getFirstName(),
            inspector.getLastName(),
            inspector.getEmail(),
            inspector.getPhone(),
            inspector.getQualifications(),
            inspector.getAssignedDistrict(),
            inspector.getEmploymentStatus()
        };
        tableModel.addRow(row);
        
        // Select the row in the table
        inspectorTable.setRowSelectionInterval(0, 0);
        
        // Populate the form fields
        idNumberField.setText(inspector.getInspectorIdNumber());
        firstNameField.setText(inspector.getFirstName());
        lastNameField.setText(inspector.getLastName());
        emailField.setText(inspector.getEmail());
        phoneField.setText(inspector.getPhone() != null ? inspector.getPhone() : "");
        qualificationsField.setText(inspector.getQualifications() != null ? inspector.getQualifications() : "");
        districtField.setText(inspector.getAssignedDistrict());
        statusComboBox.setSelectedItem(inspector.getEmploymentStatus());
        
        JOptionPane.showMessageDialog(this, 
                "Inspector found successfully!",
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
                
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
                "Invalid Inspector ID format! Please enter a valid number.",
                "Invalid Input", 
                JOptionPane.ERROR_MESSAGE);
        txtInspectorID.requestFocus();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();}
    
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToDashboardActionPerformed
    this.dispose();
    new DashboardForm().setVisible(true);
    }//GEN-LAST:event_btnBackToDashboardActionPerformed

    private boolean validateInputs() {
    if (idNumberField.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Inspector ID number is required!",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        idNumberField.requestFocus();
        return false;
    }
    if (firstNameField.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "First name is required!",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        firstNameField.requestFocus();
        return false;
    }
    if (lastNameField.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Last name is required!",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        lastNameField.requestFocus();
        return false;
    }
    if (emailField.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Email is required!",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        emailField.requestFocus();
        return false;
    }
    
    // ADD PHONE VALIDATION HERE
    if (phoneField.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Phone number is required!",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        phoneField.requestFocus();
        return false;
    }
    
    if (!isValidRwandanPhone(phoneField.getText().trim())) {
        JOptionPane.showMessageDialog(this, 
                "Invalid phone number!\n" +
                "Rwandan phone numbers must be 10 digits starting with:\n" +
                "ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ MTN: 078 or 079\n" +
                "ÃƒÂ¢Ã¢â€šÂ¬Ã‚Â¢ Airtel: 073 or 072\n" +
                "Example: 0781234567 or 0733456789",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        phoneField.requestFocus();
        return false;
    }
    
    if (districtField.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Assigned district is required!",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
        districtField.requestFocus();
        return false;
    }
    return true;
}

    private void clearFields() {
        idNumberField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        emailField.setText("");
        phoneField.setText("");
        qualificationsField.setText("");
        districtField.setText("");
        statusComboBox.setSelectedIndex(0);
        inspectorTable.clearSelection();
    }
    // ADD THIS NEW METHOD HERE
private boolean isValidRwandanPhone(String phone) {
    // Remove any spaces, dashes, or parentheses
    phone = phone.replaceAll("[\\s\\-()]", "");
    
    // Remove country code if present
    if (phone.startsWith("+250")) {
        phone = "0" + phone.substring(4);
    } else if (phone.startsWith("250")) {
        phone = "0" + phone.substring(3);
    }
    
    // Check if it's exactly 10 digits starting with 07
    if (!phone.matches("^07\\d{8}$")) {
        return false;
    }
    
    // Extract the prefix (first 3 digits after 0)
    String prefix = phone.substring(0, 3);
    
    // Valid Rwandan mobile prefixes
    // MTN: 078, 079
    // Airtel: 073, 072
    return prefix.equals("078") ||  // MTN
           prefix.equals("079") ||  // MTN
           prefix.equals("073") ||  // Airtel
           prefix.equals("072");    // Airtel/Tigo
}

private void styleForm() {
    // Define color scheme
    Color wintergreenDream = new Color(95, 140, 130);    // Main background
    Color laurelGreen = new Color(168, 186, 169);        // Panel background
    Color dutchWhite = new Color(229, 221, 194);         // Input fields
    Color darkAccent = new Color(40, 60, 55);            // Text and buttons
    Color buttonHover = new Color(75, 120, 110);         // Button hover state
    
    // Set main form background
    getContentPane().setBackground(wintergreenDream);
    
    // Style all panels
    jPanel1.setBackground(laurelGreen);
    jPanel2.setBackground(laurelGreen);
    jPanel3.setBackground(wintergreenDream);
    jPanel4.setBackground(laurelGreen);
    
    // Style panel borders
    jPanel2.setBorder(BorderFactory.createTitledBorder(
        BorderFactory.createLineBorder(darkAccent, 2),
        "Inspector Details",
        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
        javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new Font("Dialog", Font.BOLD, 12),
        darkAccent
    ));
    
    jPanel4.setBorder(BorderFactory.createTitledBorder(
        BorderFactory.createLineBorder(darkAccent, 2),
        "Inspector Search",
        javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
        javax.swing.border.TitledBorder.DEFAULT_POSITION,
        new Font("Dialog", Font.BOLD, 12),
        darkAccent
    ));
    
    // Style all labels
    styleLabel(jLabel1, darkAccent, 18, Font.BOLD);
    styleLabel(jLabel2, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel3, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel4, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel5, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel6, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel7, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel8, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel9, darkAccent, 12, Font.PLAIN);
    styleLabel(jLabel10, darkAccent, 12, Font.PLAIN);
    
    // Style all text fields
    styleTextField(idNumberField, dutchWhite, darkAccent);
    styleTextField(firstNameField, dutchWhite, darkAccent);
    styleTextField(lastNameField, dutchWhite, darkAccent);
    styleTextField(emailField, dutchWhite, darkAccent);
    styleTextField(phoneField, dutchWhite, darkAccent);
    styleTextField(qualificationsField, dutchWhite, darkAccent);
    styleTextField(districtField, dutchWhite, darkAccent);
    styleTextField(txtInspectorID, dutchWhite, darkAccent);
    
    // Style combo box
    statusComboBox.setBackground(dutchWhite);
    statusComboBox.setForeground(darkAccent);
    statusComboBox.setFont(new Font("Dialog", Font.PLAIN, 12));
    statusComboBox.setBorder(BorderFactory.createLineBorder(darkAccent, 1));
    
    // Style all buttons
    styleButton(addButton, wintergreenDream, Color.WHITE, buttonHover);
    styleButton(updateButton, wintergreenDream, Color.WHITE, buttonHover);
    styleButton(deleteButton, new Color(180, 80, 80), Color.WHITE, new Color(200, 60, 60));
    styleButton(clearButton, laurelGreen, darkAccent, new Color(150, 170, 151));
    styleButton(btnSearch, wintergreenDream, Color.WHITE, buttonHover);
    styleButton(btnBackToDashboard, darkAccent, Color.WHITE, new Color(60, 80, 75));
    
    // Style table
    inspectorTable.setBackground(dutchWhite);
    inspectorTable.setForeground(darkAccent);
    inspectorTable.setSelectionBackground(wintergreenDream);
    inspectorTable.setSelectionForeground(Color.WHITE);
    inspectorTable.setGridColor(laurelGreen);
    inspectorTable.setFont(new Font("Dialog", Font.PLAIN, 11));
    inspectorTable.getTableHeader().setBackground(wintergreenDream);
    inspectorTable.getTableHeader().setForeground(Color.WHITE);
    inspectorTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 12));
    inspectorTable.setRowHeight(25);
    
    // Style scroll pane
    jScrollPane1.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
    jScrollPane1.getViewport().setBackground(dutchWhite);
}

private void styleLabel(javax.swing.JLabel label, Color foreground, int size, int style) {
    label.setForeground(foreground);
    label.setFont(new Font("Dialog", style, size));
}

private void styleTextField(javax.swing.JTextField textField, Color background, Color foreground) {
    textField.setBackground(background);
    textField.setForeground(foreground);
    textField.setCaretColor(foreground);
    textField.setFont(new Font("Dialog", Font.PLAIN, 12));
    textField.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(foreground, 1),
        BorderFactory.createEmptyBorder(5, 8, 5, 8)
    ));
}

private void styleButton(javax.swing.JButton button, Color background, 
                        Color foreground, Color hoverColor) {
    button.setBackground(background);
    button.setForeground(foreground);
    button.setFont(new Font("Dialog", Font.BOLD, 12));
    button.setFocusPainted(false);
    button.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(foreground.darker(), 1),
        BorderFactory.createEmptyBorder(8, 15, 8, 15)
    ));
    button.setCursor(new Cursor(Cursor.HAND_CURSOR));
    
    // Add hover effect
    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(background);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton btnBackToDashboard;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField districtField;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField idNumberField;
    private javax.swing.JTable inspectorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField qualificationsField;
    private javax.swing.JComboBox statusComboBox;
    private javax.swing.JTextField txtInspectorID;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
