/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rccms.common.domain.Church;
import rccms.common.domain.Inspection;
import rccms.common.domain.InspectionDetail;
import rccms.common.domain.InspectionStandard;
import rccms.common.domain.Inspector;
import rccms.common.exception.DatabaseException;
import rccms.common.service.ChurchService;
import rccms.common.service.InspectionService;
import rccms.common.service.InspectorService;
import rccms.common.service.StandardService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;
import rccms.client.util.UserSession;
import rccms.common.domain.User;

/**
 *
 * @author IT MODERN LTD
 */
public class InspectionForm extends javax.swing.JFrame {

    private InspectionService inspectionService;
    private ChurchService churchService;
    private InspectorService inspectorService;
    private StandardService standardService;
    private DefaultTableModel standardsTableModel;
    private List<InspectionStandard> allStandards;

    /**
     * Creates new form InspectionForm
     */
    public InspectionForm() {
        initComponents();
        // Services initialized via RMI
        standardService = new StandardService(); // StandardService is a Facade, so it's OK
        // Other services will be fetched via RMI on demand

        // SET THE CORRECT MODEL FIRST (before getting the reference)
        standardsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null}, // 7 columns
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String[]{
                    "ID", "Code", "Name", "Category", "Mandatory", "Max Score", "Score" // 7 column names
                }
        ));

        // NOW get the reference to the correct model
        standardsTableModel = (DefaultTableModel) standardsTable.getModel();

        standardsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                standardsTableMouseClicked(evt);
            }
        });

        loadChurches();
        loadStandards();
        styleForm();
        setLocationRelativeTo(null);
    }

    private void loadChurches() {
        try {
            churchComboBox.removeAllItems();
            churchService = rccms.client.util.RMIClientUtil.getChurchService();
            if (churchService != null) {
                List<Church> churches = churchService.findAll();
                for (Church church : churches) {
                    churchComboBox.addItem(church.getChurchId() + " - " + church.getChurchName());
                }
            } else {
                 JOptionPane.showMessageDialog(this, "Could not connect to server to load churches.", "Connection Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error loading churches: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadStandards() {
        try {
            allStandards = standardService.getAllStandards();
            standardsTableModel.setRowCount(0);
            for (InspectionStandard standard : allStandards) {
                Object[] row = {
                    standard.getStandardId(),
                    standard.getStandardCode(),
                    standard.getStandardName(),
                    standard.getCategory(),
                    standard.isMandatory() ? "Yes" : "No",
                    standard.getMaxScore(),
                    0.0
                };
                standardsTableModel.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error loading standards: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        inspectionDateField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        churchComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scoreField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        setScoreButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        standardsTable = new javax.swing.JTable();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        notesArea = new javax.swing.JScrollPane();
        notesTextArea = new javax.swing.JTextArea();
        btnBackToDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Notes:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Inspection Date:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conduct Inspection");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Score:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Church:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Inspection Details");

        setScoreButton.setText("Set Score");
        setScoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setScoreButtonActionPerformed(evt);
            }
        });

        standardsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        standardsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                standardsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(standardsTable);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Standards List");

        notesArea.setViewportView(notesTextArea);

        btnBackToDashboard.setText("Back to Dashboard");
        btnBackToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(setScoreButton)
                                    .addGap(12, 12, 12))
                                .addComponent(notesArea)
                                .addComponent(jScrollPane1))
                            .addComponent(churchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inspectionDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(72, 72, 72))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(85, 85, 85)
                        .addComponent(cancelButton)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBackToDashboard)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnBackToDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(churchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(inspectionDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(notesArea)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(setScoreButton)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(submitButton))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setScoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setScoreButtonActionPerformed
        int selectedRow = standardsTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a standard!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double score = Double.parseDouble(scoreField.getText().trim());
            InspectionStandard standard = allStandards.get(selectedRow);

            if (score < 0 || score > standard.getMaxScore()) {
                JOptionPane.showMessageDialog(this,
                        "Score must be between 0 and " + standard.getMaxScore(),
                        "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            standardsTableModel.setValueAt(score, selectedRow, 6);
            scoreField.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid score value!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_setScoreButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (churchComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a church!",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Date inspectionDate;
        try {
            inspectionDate = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(inspectionDateField.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid date format! Use yyyy-MM-dd",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            User user = UserSession.getInstance().getUser();
            if (user == null) {
                JOptionPane.showMessageDialog(this, "No inspectors available/logged in!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (!UserSession.getInstance().isInspector()) {
                JOptionPane.showMessageDialog(this, "Only Inspectors can conduct inspection !!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            inspectorService = rccms.client.util.RMIClientUtil.getInspectorService();
            if (inspectorService == null) {
                 JOptionPane.showMessageDialog(this, "Could not connect to server.", "Connection Error", JOptionPane.ERROR_MESSAGE);
                 return;
            }
            
            Inspector inspector = inspectorService.findByUserId(user.getUserId());
            if (inspector == null) {
                 JOptionPane.showMessageDialog(this, "No Inspector profile found for this user.", "Error", JOptionPane.ERROR_MESSAGE);
                 return;
            }
            int inspectorId = inspector.getInspectorId();

            String selectedChurch = churchComboBox.getSelectedItem().toString();
            int churchId = Integer.parseInt(selectedChurch.split(" - ")[0]);

            Inspection inspection = new Inspection();
            inspection.setChurchId(churchId);
            inspection.setInspectorId(inspectorId);
            inspection.setInspectionDate(inspectionDate);
            inspection.setNotes(notesTextArea.getText().trim());

            List<InspectionDetail> details = new ArrayList<>();
            double totalScore = 0;
            double totalMaxScore = 0;

            for (int i = 0; i < standardsTableModel.getRowCount(); i++) {
                Object scoreObj = standardsTableModel.getValueAt(i, 6);
                if (scoreObj != null) {
                    InspectionDetail detail = new InspectionDetail();
                    int stdId = (Integer) standardsTableModel.getValueAt(i, 0);
                    detail.setStandardId(stdId);
                    
                    double sc; 
                    try {
                        sc = Double.parseDouble(scoreObj.toString());
                    } catch (NumberFormatException nfe) { continue; }
                    
                    detail.setScore(sc);
                    details.add(detail);
                    
                    totalScore += sc;
                    Object maxObj = standardsTableModel.getValueAt(i, 5);
                    double max = Double.parseDouble(maxObj.toString());
                    totalMaxScore += max;
                }
            }

            if (details.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter scores for at least one standard!",
                        "Validation Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            double overall = (totalMaxScore > 0) ? (totalScore / totalMaxScore) * 100 : 0;
            inspection.setOverallScore(overall);
            inspection.setStatus(overall >= 50 ? "PASSED" : "FAILED");

            inspectionService = rccms.client.util.RMIClientUtil.getInspectionService();
            int inspectionId = inspectionService.createAndGetId(inspection);
            
            if (inspectionId > 0) {
                 // Save details
                 for (InspectionDetail detail : details) {
                     detail.setInspectionId(inspectionId);
                 }
                 
                 boolean detailsSaved = inspectionService.createDetailsBatch(details);
                 if (detailsSaved) {
                     JOptionPane.showMessageDialog(this, "Inspection submitted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                     this.dispose();
                 } else {
                     JOptionPane.showMessageDialog(this, "Inspection saved but failed to save details.", "Warning", JOptionPane.WARNING_MESSAGE);
                     this.dispose();
                 }
            } else {
                 JOptionPane.showMessageDialog(this, "Failed to submit inspection.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Invalid church ID format!",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void standardsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_standardsTableMouseClicked
        int selectedRow = standardsTable.getSelectedRow();
        if (selectedRow >= 0) {
            Object scoreValue = standardsTableModel.getValueAt(selectedRow, 6);
            if (scoreValue != null) {
                scoreField.setText(scoreValue.toString());
            } else {
                scoreField.setText("");
            }
        }
    }//GEN-LAST:event_standardsTableMouseClicked

    private void btnBackToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToDashboardActionPerformed
        this.dispose();
        new DashboardForm().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnBackToDashboardActionPerformed

    private void styleForm() {
        // Define color scheme (matching InspectorManagementForm)
        Color wintergreenDream = new Color(95, 140, 130);    // Main background
        Color laurelGreen = new Color(168, 186, 169);        // Panel background
        Color dutchWhite = new Color(229, 221, 194);         // Input fields
        Color darkAccent = new Color(40, 60, 55);            // Text and buttons
        Color buttonHover = new Color(75, 120, 110);         // Button hover state

        // Set main form background
        getContentPane().setBackground(wintergreenDream);

        // Style all labels
        styleLabel(jLabel1, darkAccent, 48, Font.BOLD);  // Main title
        styleLabel(jLabel2, darkAccent, 18, Font.PLAIN);
        styleLabel(jLabel3, darkAccent, 18, Font.PLAIN);
        styleLabel(jLabel4, darkAccent, 18, Font.PLAIN);
        styleLabel(jLabel5, darkAccent, 18, Font.PLAIN);
        styleLabel(jLabel6, darkAccent, 18, Font.BOLD);
        styleLabel(jLabel7, darkAccent, 18, Font.BOLD);

        // Style text fields
        styleTextField(inspectionDateField, dutchWhite, darkAccent);
        styleTextField(scoreField, dutchWhite, darkAccent);

        // Style combo box
        churchComboBox.setBackground(dutchWhite);
        churchComboBox.setForeground(darkAccent);
        churchComboBox.setFont(new Font("Dialog", Font.PLAIN, 14));
        churchComboBox.setBorder(BorderFactory.createLineBorder(darkAccent, 1));

        // Style text area
        notesTextArea.setBackground(dutchWhite);
        notesTextArea.setForeground(darkAccent);
        notesTextArea.setCaretColor(darkAccent);
        notesTextArea.setFont(new Font("Dialog", Font.PLAIN, 12));
        notesTextArea.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(darkAccent, 1),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
        ));
        notesArea.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
        notesArea.getViewport().setBackground(dutchWhite);

        // Style table
        standardsTable.setBackground(dutchWhite);
        standardsTable.setForeground(darkAccent);
        standardsTable.setSelectionBackground(wintergreenDream);
        standardsTable.setSelectionForeground(Color.WHITE);
        standardsTable.setGridColor(laurelGreen);
        standardsTable.setFont(new Font("Dialog", Font.PLAIN, 11));
        standardsTable.setRowHeight(25);

        // Style table header
        standardsTable.getTableHeader().setBackground(wintergreenDream);
        standardsTable.getTableHeader().setForeground(Color.WHITE);
        standardsTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 12));

        // Style scroll pane
        jScrollPane1.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
        jScrollPane1.getViewport().setBackground(dutchWhite);

        // Style buttons
        styleButton(setScoreButton, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(submitButton, darkAccent, Color.WHITE, new Color(60, 80, 75));
        styleButton(cancelButton, new Color(180, 80, 80), Color.WHITE, new Color(200, 60, 60)); // Red for cancel
        styleButton(btnBackToDashboard, darkAccent, Color.WHITE, new Color(60, 80, 75));
    }

    private void styleLabel(javax.swing.JLabel label, Color foreground, int size, int style) {
        label.setForeground(foreground);
        label.setFont(new Font("Dialog", style, size));
    }

    private void styleTextField(javax.swing.JTextField textField, Color background, Color foreground) {
        textField.setBackground(background);
        textField.setForeground(foreground);
        textField.setCaretColor(foreground);
        textField.setFont(new Font("Dialog", Font.PLAIN, 14));
        textField.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground, 1),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
        ));
    }

    private void styleButton(javax.swing.JButton button, Color background,
            Color foreground, Color hoverColor) {
        button.setBackground(background);
        button.setForeground(foreground);
        button.setFont(new Font("Dialog", Font.BOLD, 12));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground.darker(), 1),
                BorderFactory.createEmptyBorder(8, 15, 8, 15)
        ));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverColor);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(background);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToDashboard;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> churchComboBox;
    private javax.swing.JTextField inspectionDateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane notesArea;
    private javax.swing.JTextArea notesTextArea;
    private javax.swing.JTextField scoreField;
    private javax.swing.JButton setScoreButton;
    private javax.swing.JTable standardsTable;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
