/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import rccms.common.domain.Inspection;
import rccms.common.service.InspectionService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;

/**
 *
 * @author IT MODERN LTD
 */
public class InspectionListForm extends javax.swing.JFrame {

    
    private InspectionService inspectionService;
    private DefaultTableModel tableModel;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    /**
     * Creates new form InspectionListForm
     */
    public InspectionListForm() {
        initComponents();
        try {
            inspectionService = rccms.client.util.RMIClientUtil.getInspectionService();
        } catch (Exception e) {
            e.printStackTrace();
        }
        tableModel = (DefaultTableModel) inspectionTable.getModel();
        
        loadInspections();
    
    styleForm();
        setLocationRelativeTo(null);
    }
    private void loadInspections() {
    tableModel.setRowCount(0);
    
    // DEBUG: Print column count
    System.out.println("Table column count: " + tableModel.getColumnCount());
    
    List<Inspection> inspections;
    try {
        if (inspectionService == null) inspectionService = rccms.client.util.RMIClientUtil.getInspectionService();
        inspections = inspectionService.findAll();
    } catch (Exception e) {
        e.printStackTrace();
        inspections = java.util.Collections.emptyList();
    }
    
    // DEBUG: Print how many inspections were retrieved
    System.out.println("Number of inspections retrieved: " + inspections.size());
    
    for (Inspection inspection : inspections) {
        Object[] row = {
            inspection.getInspectionId(),
            inspection.getChurchId(),
            inspection.getInspectorId(),
            dateFormat.format(inspection.getInspectionDate()),
            String.format("%.2f", inspection.getOverallScore()) + "%",
            inspection.getStatus(),
            inspection.getNotes(),
            inspection.getCreatedAt() != null ? dateFormat.format(inspection.getCreatedAt()) : ""
        };
        
        // DEBUG: Print each row being added
        System.out.println("Adding row: " + java.util.Arrays.toString(row));
        
        tableModel.addRow(row);
    }
    
    // DEBUG: Print final row count
    System.out.println("Table row count after loading: " + tableModel.getRowCount());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inspectionTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        btnBackToDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Inspection List");

        inspectionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "InspectionId", "ChurchId", "InspectorId", "InspectionDate", "OverallScore", "Status", "Notes", "CreatedAt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(inspectionTable);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        btnBackToDashboard.setText("Back to Dashboard");
        btnBackToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshButton)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(393, 393, 393)
                        .addComponent(btnBackToDashboard)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackToDashboard)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(closeButton))
                .addGap(178, 178, 178))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        loadInspections();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void btnBackToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToDashboardActionPerformed
        this.dispose();
    new DashboardForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackToDashboardActionPerformed

   private void styleForm() {
    // Define color scheme (matching InspectorManagementForm)
    Color wintergreenDream = new Color(95, 140, 130);    // Main background
    Color laurelGreen = new Color(168, 186, 169);        // Panel background
    Color dutchWhite = new Color(229, 221, 194);         // Input fields
    Color darkAccent = new Color(40, 60, 55);            // Text and buttons
    Color buttonHover = new Color(75, 120, 110);         // Button hover state
    
    // Set main form background
    getContentPane().setBackground(wintergreenDream);
    
    // Style the title label
    jLabel1.setForeground(darkAccent);
    jLabel1.setFont(new Font("Dialog", Font.BOLD, 36));
    
    // Style the table
    inspectionTable.setBackground(dutchWhite);
    inspectionTable.setForeground(darkAccent);
    inspectionTable.setSelectionBackground(wintergreenDream);
    inspectionTable.setSelectionForeground(Color.WHITE);
    inspectionTable.setGridColor(laurelGreen);
    inspectionTable.setFont(new Font("Dialog", Font.PLAIN, 11));
    inspectionTable.setRowHeight(25);
    
    // Style table header
    inspectionTable.getTableHeader().setBackground(wintergreenDream);
    inspectionTable.getTableHeader().setForeground(Color.WHITE);
    inspectionTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 12));
    inspectionTable.getTableHeader().setBorder(BorderFactory.createLineBorder(darkAccent, 1));
    
    // Style scroll pane
    jScrollPane2.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
    jScrollPane2.getViewport().setBackground(dutchWhite);
    
    // Style buttons with consistent theme
    styleButton(refreshButton, wintergreenDream, Color.WHITE, buttonHover);
    styleButton(closeButton, new Color(180, 80, 80), Color.WHITE, new Color(200, 60, 60)); // Red for close
    styleButton(btnBackToDashboard, darkAccent, Color.WHITE, new Color(60, 80, 75));
}

private void styleButton(javax.swing.JButton button, Color background, 
                        Color foreground, Color hoverColor) {
    button.setBackground(background);
    button.setForeground(foreground);
    button.setFont(new Font("Dialog", Font.BOLD, 12));
    button.setFocusPainted(false);
    button.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(foreground.darker(), 1),
        BorderFactory.createEmptyBorder(8, 15, 8, 15)
    ));
    button.setCursor(new Cursor(Cursor.HAND_CURSOR));
    
    // Add hover effect
    button.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            button.setBackground(hoverColor);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            button.setBackground(background);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToDashboard;
    private javax.swing.JButton closeButton;
    private javax.swing.JTable inspectionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
 }
