/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import javax.swing.JOptionPane;
import rccms.common.domain.User;
import rccms.common.exception.DatabaseException;
import rccms.common.service.AuthService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;
import rccms.client.util.UserSession;

/**
 *
 * @author IT MODERN LTD
 */
public class LoginForm extends javax.swing.JFrame {

    private AuthService authService;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        authService = new AuthService();
        styleForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        registerLinkLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.darkGray);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RCCMS Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Username:");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Password:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        registerLinkLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerLinkLabel.setText("Don't have an account? Register");
        registerLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLinkLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(passwordField)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(registerLinkLabel)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(registerLinkLabel)
                .addGap(15, 15, 15))
        );

        jPanel1.setBounds(30, 250, 730, 480);
        getContentPane().add(jPanel1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("RWANDA CHURCH COMPLIANCE AND MONITORING SYSTEM");
        jLabel1.setBounds(20, 90, 700, 50);
        getContentPane().add(jLabel1);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT MODERN LTD\\Downloads\\3d-rendering-church-building(1) (2).jpg")); // NOI18N
        jLabel4.setBounds(0, 0, 800, 800);
        getContentPane().add(jLabel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLinkLabelMouseClicked
        this.dispose();
        RegisterForm registerForm = new RegisterForm();
        registerForm.setVisible(true);
    }//GEN-LAST:event_registerLinkLabelMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter both username and password.",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            User user = authService.login(username, password);
            if (user != null) {
                UserSession.getInstance().setUser(user);
                JOptionPane.showMessageDialog(this,
                        "Login successful! Welcome " + user.getUsername(),
                        "Success", JOptionPane.INFORMATION_MESSAGE);

                this.dispose();
                DashboardForm dashboard = new DashboardForm();
                dashboard.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Invalid username or password. Please try again.",
                        "Login Failed", JOptionPane.ERROR_MESSAGE);
                passwordField.setText("");
            }
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    "Validation Error: " + e.getMessage(),
                    "Validation Failed", JOptionPane.WARNING_MESSAGE);
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this,
                    "Database Error: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    /**
     * Apply custom styling to the login form
     */
    private void styleForm() {
        // Color palette: Wintergreen Dream, Laurel Green, Dutch White
        Color wintergreenDream = new Color(95, 140, 130);  // Main background
        Color laurelGreen = new Color(168, 186, 169);      // Panel background
        Color dutchWhite = new Color(229, 221, 194);       // Light accent
        Color darkAccent = new Color(70, 105, 95);         // Dark buttons

        // Set form background color
        //this.getContentPane().setBackground(wintergreenDream);
        //jPanel1.setBackground(laurelGreen);
 

        // Style other labels
        jLabel2.setForeground(darkAccent);
        jLabel2.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jLabel3.setForeground(darkAccent);
        jLabel3.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // Style input fields
        usernameField.setBackground(dutchWhite);
        usernameField.setForeground(Color.BLACK);
        usernameField.setFont(new Font("Segoe UI", Font.BOLD, 13));
        passwordField.setBackground(dutchWhite);
        passwordField.setForeground(Color.BLACK);
        passwordField.setFont(new Font("Segoe UI", Font.BOLD, 13));
// Style register link
        registerLinkLabel.setForeground(Color.WHITE);
        registerLinkLabel.setFont(new Font("Segoe UI", Font.BOLD, 14));
        registerLinkLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
// Style buttons
        styleButton(loginButton, darkAccent, wintergreenDream); 
    }

    /**
     * Apply styling to a button with hover effects
     */
    private void styleButton(javax.swing.JButton button, Color bg, Color hoverBg) {
        button.setBackground(bg);
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Segoe UI", Font.BOLD, 14));
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        button.setFocusPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverBg);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(bg);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel registerLinkLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
