/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import javax.swing.JOptionPane;
import rccms.common.exception.DatabaseException;
import rccms.common.exception.ValidationException;
import rccms.common.service.AuthService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;

/**
 *
 * @author IT MODERN LTD
 */
public class RegisterForm extends javax.swing.JFrame {

    private AuthService authService;

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        authService = new AuthService();

        authService = new AuthService();
        styleForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        confirmPasswordField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        loginLinkLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RCCMS REGISTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("User Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Password");

        registerButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Confirm Password");

        loginLinkLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        loginLinkLabel.setText("Have an account? Login");
        loginLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLinkLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                        .addComponent(confirmPasswordField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(loginLinkLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(loginLinkLabel)
                .addGap(24, 24, 24))
        );

        jPanel2.setBounds(20, 145, 710, 480);
        getContentPane().add(jPanel2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("RWANDA CHURCH COMPLIANCE AND MONITORING SYSTEM");
        jLabel2.setBounds(70, 60, 600, 50);
        getContentPane().add(jLabel2);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IT MODERN LTD\\Downloads\\3d-rendering-church-building(1) (2).jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, 0, 710, 800);
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());

        try {
            authService.register(username, password, confirmPassword, "ADMIN");
            JOptionPane.showMessageDialog(this,
                    "Registration successful! You can now login with your credentials.",
                    "Registration Success", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
        } catch (ValidationException e) {
            JOptionPane.showMessageDialog(this,
                    "Validation Error: " + e.getMessage(),
                    "Validation Failed", JOptionPane.WARNING_MESSAGE);
        } catch (DatabaseException e) {
            JOptionPane.showMessageDialog(this,
                    "Database Error: " + e.getMessage(),
                    "Database Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Unexpected Error: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLinkLabelMouseClicked
        this.dispose();
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
    }//GEN-LAST:event_loginLinkLabelMouseClicked

    /**
     * Apply custom styling to the register form
     */
    private void styleForm() {
        // Color palette: Wintergreen Dream, Laurel Green, Dutch White
        Color wintergreenDream = new Color(95, 140, 130);  // Main background
        Color laurelGreen = new Color(168, 186, 169);      // Panel background
        Color dutchWhite = new Color(229, 221, 194);       // Light accent
        Color darkAccent = new Color(70, 105, 95);         // Dark buttons

        // Set form background color
        this.getContentPane().setBackground(wintergreenDream);
        jPanel2.setBackground(laurelGreen);

        // Style all labels
        jLabel6.setForeground(darkAccent);
        jLabel6.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jLabel7.setForeground(darkAccent);
        jLabel7.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jLabel8.setForeground(darkAccent);
        jLabel8.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // Style input fields
        usernameField.setBackground(dutchWhite);
        usernameField.setForeground(darkAccent);
        usernameField.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        passwordField.setBackground(dutchWhite);
        passwordField.setForeground(darkAccent);
        passwordField.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        confirmPasswordField.setBackground(dutchWhite);
        confirmPasswordField.setForeground(darkAccent);
        confirmPasswordField.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        // Style login link
        loginLinkLabel.setForeground(darkAccent);
        loginLinkLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        loginLinkLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Style buttons
        styleButton(registerButton, darkAccent, wintergreenDream);
    }

    /**
     * Apply styling to a button with hover effects
     */
    private void styleButton(javax.swing.JButton button, Color bg, Color hoverBg) {
        button.setBackground(bg);
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Segoe UI", Font.BOLD, 14));
        button.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        button.setFocusPainted(false);
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverBg);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(bg);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginLinkLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
