/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rccms.client.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rccms.common.domain.InspectionStandard;
import rccms.common.service.StandardService;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import java.awt.Cursor;

/**
 *
 * @author IT MODERN LTD
 */
public class StandardManagementForm extends javax.swing.JFrame {

    private StandardService standardService;
    private DefaultTableModel tableModel;
    private static final String SEARCH_PLACEHOLDER = "Enter Standard ID...";
    private Color darkAccent = new Color(40, 60, 55);

    /**
     * Creates new form StandardManagementForm
     */
    public StandardManagementForm() {
        initComponents();
        standardService = new StandardService();

        // FIXED: Changed to DISPOSE_ON_CLOSE instead of EXIT_ON_CLOSE
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // FIRST: Create and set the NEW model with correct columns
        standardTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "Code", "Name", "Description", "Category", "Mandatory", "Max Score"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make table read-only
            }
        });

        // SECOND: Get the reference to the NEW model
        tableModel = (DefaultTableModel) standardTable.getModel();

        // THIRD: Load data into the NEW model
        loadStandards();

        // FOURTH: Apply styling
        styleForm();
        setLocationRelativeTo(null);

        // ADDED: Setup search field placeholder
        setupSearchFieldPlaceholder();
    }

    private void loadStandards() {
        tableModel.setRowCount(0);
        List<InspectionStandard> standards = standardService.getAllStandards();
        for (InspectionStandard standard : standards) {
            Object[] row = {
                standard.getStandardId(),
                standard.getStandardCode(),
                standard.getStandardName(),
                standard.getDescription(),
                standard.getCategory(),
                standard.isMandatory() ? "Yes" : "No",
                standard.getMaxScore()
            };
            tableModel.addRow(row);
        }
    }

// ADDED: Placeholder handling for search field
    private void setupSearchFieldPlaceholder() {
        txtSearchId.setText(SEARCH_PLACEHOLDER);
        txtSearchId.setForeground(Color.GRAY);

        txtSearchId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtSearchId.getText().equals(SEARCH_PLACEHOLDER)) {
                    txtSearchId.setText("");
                    txtSearchId.setForeground(darkAccent);
                }
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtSearchId.getText().trim().isEmpty()) {
                    txtSearchId.setText(SEARCH_PLACEHOLDER);
                    txtSearchId.setForeground(Color.GRAY);
                }
            }
        });
    }

    // ADDED: Helper method to highlight found standard in table
    private void highlightStandardInTable(int standardId) {
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if ((Integer) tableModel.getValueAt(i, 0) == standardId) {
                standardTable.setRowSelectionInterval(i, i);
                standardTable.scrollRectToVisible(standardTable.getCellRect(i, 0, true));
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descriptionArea = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        mandatoryCheckBox = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        maxScoreField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        standardTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnBackToDashboard = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSearchId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Inspection Standards Management");

        jLabel2.setText("Standard Code:");

        codeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Standard Name:");

        jLabel4.setText("Description:");

        descriptionArea.setViewportView(descriptionTextArea);

        jLabel5.setText("Category:");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAFETY", "LEGAL", "OPERATIONAL", "STRUCTURAL" }));

        jLabel6.setText("Mandatory:");

        jLabel7.setText("Max Score:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        standardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        standardTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                standardTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(standardTable);

        jLabel8.setText("Standards List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(updateButton)
                        .addGap(33, 33, 33)
                        .addComponent(deleteButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addButton)
                                        .addComponent(jLabel7)))
                                .addGap(178, 178, 178)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(codeField)
                                        .addComponent(descriptionArea))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(clearButton)
                                        .addComponent(maxScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(121, 121, 121)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mandatoryCheckBox))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(82, 82, 82))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descriptionArea)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(mandatoryCheckBox)))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(maxScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(updateButton)
                        .addComponent(addButton)
                        .addComponent(deleteButton))
                    .addComponent(clearButton))
                .addGap(25, 25, 25))
        );

        btnBackToDashboard.setText("Back to Dashboard");
        btnBackToDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToDashboardActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Standards Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel10.setText("Standard Id");

        txtSearchId.setText("jTextField1");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch))
                    .addComponent(jLabel9)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackToDashboard)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackToDashboard)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (!validateInputs()) {
            return;
        }

        try {
            InspectionStandard standard = new InspectionStandard();
            standard.setStandardCode(codeField.getText().trim());
            standard.setStandardName(nameField.getText().trim());
            standard.setDescription(descriptionTextArea.getText().trim());
            standard.setCategory(categoryComboBox.getSelectedItem().toString());
            standard.setMandatory(mandatoryCheckBox.isSelected());
            standard.setMaxScore(Integer.parseInt(maxScoreField.getText().trim()));

            if (standard.getMaxScore() <= 0) {
                JOptionPane.showMessageDialog(this, "Max score must be greater than 0!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (standardService.standardCodeExists(standard.getStandardCode())) {
                JOptionPane.showMessageDialog(this, "Standard code already exists!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (standardService.createStandard(standard)) {
                JOptionPane.showMessageDialog(this, "Standard added successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadStandards();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add standard!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid max score value!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        int selectedRow = standardTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a standard to update!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validateInputs()) {
            return;
        }

        try {
            int standardId = (Integer) tableModel.getValueAt(selectedRow, 0);
            InspectionStandard standard = standardService.getStandardById(standardId);

            if (standard == null) {
                JOptionPane.showMessageDialog(this, "Standard not found!",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            standard.setStandardCode(codeField.getText().trim());
            standard.setStandardName(nameField.getText().trim());
            standard.setDescription(descriptionTextArea.getText().trim());
            standard.setCategory(categoryComboBox.getSelectedItem().toString());
            standard.setMandatory(mandatoryCheckBox.isSelected());
            standard.setMaxScore(Integer.parseInt(maxScoreField.getText().trim()));

            if (standardService.updateStandard(standard)) {
                JOptionPane.showMessageDialog(this, "Standard updated successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadStandards();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update standard!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid max score value!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = standardTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a standard to delete!",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int option = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this standard?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            int standardId = (Integer) tableModel.getValueAt(selectedRow, 0);
            if (standardService.deleteStandard(standardId)) {
                JOptionPane.showMessageDialog(this, "Standard deleted successfully!",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
                loadStandards();
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete standard!",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearFields();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void standardTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_standardTableMouseClicked
        int selectedRow = standardTable.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                codeField.setText(tableModel.getValueAt(selectedRow, 1).toString());
                nameField.setText(tableModel.getValueAt(selectedRow, 2).toString());
                descriptionTextArea.setText(tableModel.getValueAt(selectedRow, 3).toString());
                categoryComboBox.setSelectedItem(tableModel.getValueAt(selectedRow, 4).toString());
                mandatoryCheckBox.setSelected("Yes".equals(tableModel.getValueAt(selectedRow, 5).toString()));
                maxScoreField.setText(tableModel.getValueAt(selectedRow, 6).toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error loading standard data: " + e.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_standardTableMouseClicked

    private void btnBackToDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToDashboardActionPerformed
        this.dispose();
        new DashboardForm().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackToDashboardActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchText = txtSearchId.getText().trim();

        // Check if placeholder text is present
        if (searchText.isEmpty() || searchText.equals(SEARCH_PLACEHOLDER)) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a Standard ID to search!",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            txtSearchId.requestFocus();
            return;
        }

        try {
            int standardId = Integer.parseInt(searchText);
            InspectionStandard standard = standardService.getStandardById(standardId);

            if (standard != null) {
                // Populate form fields
                codeField.setText(standard.getStandardCode());
                nameField.setText(standard.getStandardName());
                descriptionTextArea.setText(standard.getDescription());
                categoryComboBox.setSelectedItem(standard.getCategory());
                mandatoryCheckBox.setSelected(standard.isMandatory());
                maxScoreField.setText(String.valueOf(standard.getMaxScore()));

                // Highlight in table
                highlightStandardInTable(standardId);

                JOptionPane.showMessageDialog(this,
                        "Standard found and loaded successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "No standard found with ID: " + standardId,
                        "Not Found",
                        JOptionPane.INFORMATION_MESSAGE);
                clearFields();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Please enter a valid numeric Standard ID!",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            txtSearchId.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private boolean validateInputs() {
        if (codeField.getText().trim().isEmpty()
                || nameField.getText().trim().isEmpty()
                || descriptionTextArea.getText().trim().isEmpty()
                || maxScoreField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!",
                    "Validation Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private void clearFields() {
        codeField.setText("");
        nameField.setText("");
        descriptionTextArea.setText("");
        categoryComboBox.setSelectedIndex(0);
        mandatoryCheckBox.setSelected(false);
        maxScoreField.setText("");
        standardTable.clearSelection();
    }

    private void styleForm() {
        // Define color scheme (matching all other forms)
        Color wintergreenDream = new Color(95, 140, 130);    // Main background
        Color laurelGreen = new Color(168, 186, 169);        // Panel background
        Color dutchWhite = new Color(229, 221, 194);         // Input fields
        Color darkAccent = new Color(40, 60, 55);            // Text and buttons
        Color buttonHover = new Color(75, 120, 110);         // Button hover state

        // Set main form background
        getContentPane().setBackground(wintergreenDream);

        // Style main panel
        jPanel1.setBackground(laurelGreen);
        jPanel1.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(darkAccent, 2),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));

        // Style all labels
        jLabel1.setForeground(darkAccent);
        jLabel1.setFont(new Font("Dialog", Font.BOLD, 24));

        styleLabel(jLabel2, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel3, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel4, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel5, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel6, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel7, darkAccent, 12, Font.PLAIN);
        styleLabel(jLabel8, darkAccent, 14, Font.BOLD);

        // Style text fields
        styleTextField(codeField, dutchWhite, darkAccent);
        styleTextField(nameField, dutchWhite, darkAccent);
        styleTextField(maxScoreField, dutchWhite, darkAccent);

        // Style text area
        descriptionTextArea.setBackground(dutchWhite);
        descriptionTextArea.setForeground(darkAccent);
        descriptionTextArea.setCaretColor(darkAccent);
        descriptionTextArea.setFont(new Font("Dialog", Font.PLAIN, 12));
        descriptionTextArea.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(darkAccent, 1),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
        ));
        descriptionArea.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
        descriptionArea.getViewport().setBackground(dutchWhite);

        // Style combo box
        categoryComboBox.setBackground(dutchWhite);
        categoryComboBox.setForeground(darkAccent);
        categoryComboBox.setFont(new Font("Dialog", Font.PLAIN, 12));
        categoryComboBox.setBorder(BorderFactory.createLineBorder(darkAccent, 1));

        // Style checkbox
        mandatoryCheckBox.setBackground(laurelGreen);
        mandatoryCheckBox.setForeground(darkAccent);
        mandatoryCheckBox.setFont(new Font("Dialog", Font.PLAIN, 12));
        mandatoryCheckBox.setFocusPainted(false);

        // Style table
        standardTable.setBackground(dutchWhite);
        standardTable.setForeground(darkAccent);
        standardTable.setSelectionBackground(wintergreenDream);
        standardTable.setSelectionForeground(Color.WHITE);
        standardTable.setGridColor(laurelGreen);
        standardTable.setFont(new Font("Dialog", Font.PLAIN, 11));
        standardTable.setRowHeight(25);

        // Style table header
        standardTable.getTableHeader().setBackground(wintergreenDream);
        standardTable.getTableHeader().setForeground(Color.WHITE);
        standardTable.getTableHeader().setFont(new Font("Dialog", Font.BOLD, 12));

        // Style scroll pane
        jScrollPane1.setBorder(BorderFactory.createLineBorder(darkAccent, 2));
        jScrollPane1.getViewport().setBackground(dutchWhite);

        // Style buttons with smart color coding
        styleButton(addButton, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(updateButton, wintergreenDream, Color.WHITE, buttonHover);
        styleButton(deleteButton, new Color(180, 80, 80), Color.WHITE, new Color(200, 60, 60)); // Red for delete
        styleButton(clearButton, laurelGreen, darkAccent, new Color(150, 170, 151));
        styleButton(btnBackToDashboard, darkAccent, Color.WHITE, new Color(60, 80, 75));
        styleButton(btnBackToDashboard, darkAccent, Color.WHITE, new Color(60, 80, 75));
    }

    private void styleLabel(javax.swing.JLabel label, Color foreground, int size, int style) {
        label.setForeground(foreground);
        label.setFont(new Font("Dialog", style, size));
    }

    private void styleTextField(javax.swing.JTextField textField, Color background, Color foreground) {
        textField.setBackground(background);
        textField.setForeground(foreground);
        textField.setCaretColor(foreground);
        textField.setFont(new Font("Dialog", Font.PLAIN, 12));
        textField.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground, 1),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)
        ));
    }

    private void styleButton(javax.swing.JButton button, Color background,
            Color foreground, Color hoverColor) {
        button.setBackground(background);
        button.setForeground(foreground);
        button.setFont(new Font("Dialog", Font.BOLD, 12));
        button.setFocusPainted(false);
        button.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(foreground.darker(), 1),
                BorderFactory.createEmptyBorder(8, 15, 8, 15)
        ));
        button.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setBackground(hoverColor);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setBackground(background);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton btnBackToDashboard;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField codeField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane descriptionArea;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mandatoryCheckBox;
    private javax.swing.JTextField maxScoreField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTable standardTable;
    private javax.swing.JTextField txtSearchId;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
